### ISSUE TITLE
Push back to same branch

### ISSUE THREAD

**Issue by sidey79** [tool3/ncc#15]
I tried your action and got an errror:

```
/usr/bin/git pull origin HEAD:ncc
From https://github.com/fhem/fhem-controls-actions
 ! [rejected]                   -> ncc  (non-fast-forward)
Error: ncc failed! The process '/usr/bin/git' failed with exit code 1
```

The branch the job is running has the name `ncc` and i tried to push back to the same branch

Here is my job configuration

```
  # generate new package
  ncc:
    needs: actiontest
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Extract branch name
      uses: vazco/github-actions-branch-name@v1
      id: branch
    - name: Prepare Node.js 
      uses: actions/setup-node@v2.4.1
    - uses: tool3/ncc@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src: 'main.js'
        ncc_args: '-o, dist, --source-map, --license, licenses.txt'
        branch: ${{ steps.branch.outputs.branch_name }}
```

Any idea how to make this working?
Pushing to a new not existing branch does also not work.

Is there a way to updated a feature branch instead of a "main" or "master" branch?
